<a href="https://colab.research.google.com/github/JayRiv25/InflacionCOVID/blob/main/Inflaci%C3%B3n_Post_COVID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#1 Datos COVID
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#Carga de datos
#NOTA: Separa la fecha 'date' en mes y año
df = pd.read_csv("/content/covid_global.csv", low_memory=False)
df.head(100)

,country,date,inflation_rate,interest_rate,oil_price,gdp_growth,unemployment_rate,money_supply_m2,exchange_rate_usd,food_price_index,supply_chain_index
0,USA,2020-01,0.33,5.76,34.44,0.34,5.97,10558.0,69.95,94.29,3.66
1,USA,2020-02,4.12,4.33,44.75,0.02,5.80,6952.0,71.03,78.60,3.91
2,USA,2020-03,2.75,4.24,52.80,0.30,7.45,10244.0,71.00,102.91,3.70
3,USA,2020-04,4.36,4.52,39.19,2.28,5.23,9989.0,83.52,110.92,3.23
4,USA,2020-05,2.73,3.17,41.09,3.05,5.96,7982.0,70.10,86.53,3.94
...,...,...,...,...,...,...,...,...,...,...,...
95,VNM,2022-12,4.22,2.03,136.94,3.17,6.16,11070.0,92.17,140.10,1.19
96,VNM,2023-01,5.69,3.54,63.97,1.96,5.22,12914.0,98.51,129.84,1.13
97,VNM,2023-02,4.94,2.43,70.75,6.69,5.58,15715.0,95.73,126.41,1.26
98,VNM,2023-03,5.36,2.91,81.56,5.76,5.65,15773.0,93.67,128.33,1.75
99,VNM,2023-04,4.76,1.77,68.46,5.56,5.19,11977.0,86.67,130.46,1.68

In [5]:
df.shape

(100000, 11)

In [6]:
df.isnull().any().any()

np.False_

In [7]:
df.isnull().sum()

country               0
date                  0
inflation_rate        0
interest_rate         0
oil_price             0
gdp_growth            0
unemployment_rate     0
money_supply_m2       0
exchange_rate_usd     0
food_price_index      0
supply_chain_index    0
dtype: int64

In [8]:
#Agrupación de las columnas por tipo de datos
tipos = df.columns.to_series().groupby(df.dtypes).groups

#Conociendo la lista de columnas categóricas
ctext = tipos[np.dtype('object')]
len(ctext) #Cantidad de columnas con datos categóricos

2

In [9]:
#Conociendo la lista de columnas numéricas
columnas = df.columns
cnum = list(set(columnas) - set(ctext))
len(cnum)

9